id: IC98B5A99
legacy_id: P004471
ocr_import_info:
  bdrc_scan_id: W1KG25307
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:43:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:12:09.956730+00:00'
last_modified: 2022-08-31 22:12:43.954905
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25307
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25307
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དོན་ཡོད་མཁས་གྲུབ།
  author: ཞོག་དཀའ་བཅུ་དོན་ཡོད་མཁས་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.7913959921927883
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG25310:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25310
      total_pages: 460
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG25310.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9483631669264342
    legacy_id: v002
  I1KG25309:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25309
      total_pages: 422
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25309.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.6987481315012878
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
