id: P004471
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:24:33.656436
source_metadata:
  id: bdr:W1KG25307
  title: གསུང་འབུམ།  དོན་ཡོད་མཁས་གྲུབ།
  author: ''
  volumes:
    44579c9110de46b983c8dcd535cb8064:
      image_group_id: I1KG25309
      title: ''
      volume_number: 1
      total_pages: 422
      base_file: v001.txt
    61a72ac5064143058aa839676d8cb815:
      image_group_id: I1KG25310
      title: ''
      volume_number: 2
      total_pages: 460
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
